#!/bin/busybox sh

# Deploy busybox ln
/bin/busybox --install -s

echo "Mounting /dev, /proc and /sys ..."
mount -t devtmpfs none -o mode=755 /dev
mount -t proc none /proc
mount -t sysfs none /sys
ln -s /proc/self/fd /dev/fd

# Do your stuff here
echo "This script just mounts and boots the rootfs, nothing else!"

# Mount the root filesystem.
mkdir -p /mnt/root
mount -o ro /dev/ps3dd2 /mnt/root

# Clean up.
umount /proc
umount /sys

# Boot the real thing.
exec switch_root /mnt/root /sbin/init

# FAILED!
echo -e "Failed to boot !"
exec sh
